# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('currency', models.TextField(default='₴', max_length=10)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('photo', models.ImageField(default=django.utils.timezone.now, upload_to='gallery')),
            ],
        ),
    ]
